### PR TITLE
Refactored to service objects

### PR DESCRIPTION
**Pull request by dg-ratiodata**
As discussed here cucumber/cucumber-ruby#932. This now handles invalid input from user, e.g. 1 (Integer) as class for event.

@mattwynne So now we can discuss it here.

### CODE REVIEW

**Comment by dg-ratiodata** [comment]
Suggestions regarding `default_namespace`? Bettter a parameter of `#new` or better the first parameter of `#transform`.

**Comment by dg-ratiodata** [comment]
I would leave the specs as they are for now and making a change if we, you, me need to change the library.

**Comment by dg-ratiodata** [comment]
> We should assume that user-defined NameResolvers will follow the protocol and never return nil. Otherwise we have to clutter up our code.

But what's the difference between [this check](https://github.com/fedux-org/event-bus/blob/master/lib/event/bus.rb#L36) and [that one](https://github.com/fedux-org/event-bus/blob/master/lib/event/bus.rb#L41) from your point of view. Both enforce some kind of a protocol on user input.

Sure, I can see, that adding lots and lots of checks makes our code harder to read, but at least for now it's just one check and a clear error message to the user about what went wrong + what we expect from her/him to fix.

**Comment by mattwynne** [comment]
Well IMO the NameResolver protocol can be enforced by specs and then assumed. I don't like seeing nil checks in my code, I think they're noise.

**Comment by dg-ratiodata** [comment]
Do you think our test suite's coverage is enough for that? I updated the tests and rearranged them to make them easier to read.

**Comment by dg-ratiodata** [comment]
What about adding [such](https://github.com/egonSchiele/contracts.ruby) a library to the code base? Any thoughts about that. I use it in some other projects. It's "easy" to use/extend and makes the argument/return value types of methods much clearer.

**Pull request merged**
